name: Link Check (Lychee)

on:
  workflow_dispatch: # Disable automatic runs for now

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lychee-app/lychee-action@v2
        with:
          args: --verbose --no-progress .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
